paths:
  rxnx_train: "data/raw/summary_rxnx_train_all.txt"
  rxnx_test:  "data/raw/summary_rxnx_test_all.txt"
  psi_train:  "data/raw/summary_psi_train_all.txt"
  psi_test:   "data/raw/summary_psi_test_all.txt"
  dispx_s12_train: "data/raw/summary_dispx_train_step12.txt"
  dispx_s12_test:  "data/raw/summary_dispx_test_step12.txt"
  processed_dir: "data/processed"
  reports_dir: "reports"

io:
  sep: null
  engine: "python"
  chunksize: 10000

params:
  final_step: 12
  drop_threshold: 0.20
  compute_abs_displacement: true

subset:
  enable: true
  train: 3000
  test: 1000

repro:
  seed: 42

outputs:
  train_csv: "data/processed/features_train_compact.csv"
  test_csv:  "data/processed/features_test_compact.csv"
